version: '3.8'

services:
  parser:
    image: //url/a/parser_image
    container_name: parser
    ports:
      - "8081:8080"

  snippets:
    image: //url/a/snippets_image
    container_name: snippets
    ports:
      - "8082:8080"
    environment:
      DB_USER: ${SNIPPETS_USER}
      DB_PASSWORD: ${SNIPPETS_PASSWORD}
      DB_NAME: ${SNIPPETS_NAME}
      DB_HOST: ${SNIPPETS_HOST}
      DB_PORT: ${SNIPPETS_PORT}
    depends_on:
      - snippets_db

  snippets_db:
    image: postgres:14
    container_name: snippets_db
    ports:
      - "${SNIPPETS_PORT}:5432"
    environment:
      POSTGRES_USER: ${SNIPPETS_USER}
      POSTGRES_PASSWORD: ${SNIPPETS_PASSWORD}
      POSTGRES_DB: ${SNIPPETS_NAME}
    volumes:
      - pgdata_snippets:/var/lib/postgresql/data

  permissions:
    image: //url/a/permissions_image
    container_name: permissions
    ports:
      - "8083:8080"
    environment:
        DB_USER: ${PERMISSIONS_USER}
        DB_PASSWORD: ${PERMISSIONS_PASSWORD}
        DB_NAME: ${PERMISSIONS_NAME}
        DB_HOST: ${PERMISSIONS_HOST}
        DB_PORT: ${PERMISSIONS_PORT}
    depends_on:
      - permissions_db

  permissions_db:
    image: postgres:14
    container_name: permissions_db
    ports:
      - "${PERMISSIONS_PORT}:5432"
    environment:
      POSTGRES_USER: ${PERMISSIONS_USER}
      POSTGRES_PASSWORD: ${PERMISSIONS_PASSWORD}
      POSTGRES_DB: ${PERMISSIONS_NAME}
    volumes:
      - pgdata_permissions:/var/lib/postgresql/data

volumes:
  pgdata_snippets:
  pgdata_permissions:
